name: Scrape IMDb Top 250 - 21f3001166@ds.study.iitm.ac.in  # Workflow name with your email

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository by 21f3001166@ds.study.iitm.ac.in  # Checkout step with email
        uses: actions/checkout@v4

      - name: Install uv by 21f3001166@ds.study.iitm.ac.in  # Install step with email
        uses: astral-sh/setup-uv@v5

      - name: Run scraper by 21f3001166@ds.study.iitm.ac.in  # Run scraper step with email
        run: |
          uv run --with httpx,lxml,cssselect python scrape.py

      - name: Commit and push changes by 21f3001166@ds.study.iitm.ac.in  # Commit step with email
        run: |
          git config --local user.email "21f3001166@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add *.json
          git commit -m "Update IMDb Top 250 data by 21f3001166@ds.study.iitm.ac.in [skip ci]" || exit 0
          git push
