name: Scrape IMDb Top 250 - 21f3001166@ds.study.iitm.ac.in  # Workflow name with email

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Scrape IMDb - 21f3001166@ds.study.iitm.ac.in  # Job name with email

    steps:  # This needs to be plural as it's for multiple steps
      - name: Checkout repository and Install uv and Run scraper - 21f3001166@ds.study.iitm.ac.in  # Single step with email
        run: |
          # Checkout the repository
          git checkout main
          
          # Install uv
          curl -sSL https://get.uv.sh | bash
          
          # Run the scraper
          uv run --with httpx,lxml,cssselect python scrape.py

      - name: Commit and push changes - 21f3001166@ds.study.iitm.ac.in  # Commit step with email in name
        run: |
          git config --local user.email "21f3001166@ds.study.iitm.ac.in"
          git config --local user.name "github-actions[bot]"
          git add *.json
          git commit -m "Update IMDb Top 250 data by 21f3001166@ds.study.iitm.ac.in [skip ci]" || exit 0
          git push
